### ISSUE TITLE
AttributeError: module 'construct' has no attribute 'Embedded': Update constuct dependency to 2.10

### ISSUE THREAD

**Issue by gdubya** [endrebjorsvik/kaifa-meter#3]
Hi, testing out your package and got the following. Any ideas wha would cause it?

```
pi@powerpi:~ $ ./.local/bin/kaifa_meter serial /dev/ttyUSB0
Traceback (most recent call last):
  File "./.local/bin/kaifa_meter", line 6, in <module>
    from kaifa_meter.cli import cli
  File "/home/pi/.local/lib/python3.7/site-packages/kaifa_meter/cli.py", line 2, in <module>
    from kaifa_meter.reader import read_serial, read_file
  File "/home/pi/.local/lib/python3.7/site-packages/kaifa_meter/reader.py", line 5, in <module>
    from kaifa_meter.decoder import decode_frame
  File "/home/pi/.local/lib/python3.7/site-packages/kaifa_meter/decoder.py", line 107, in <module>
    c.Embedded(List2Top),
AttributeError: module 'construct' has no attribute 'Embedded'
```

**Comment by endrebjorsvik** [comment]
Hi! Thanks for reaching out!
The package is using [`construct`](https://construct.readthedocs.io/en/latest/) to parse the binary payload. [Version 2.10](https://construct.readthedocs.io/en/latest/transition210.html) of `construct` has removed support for the `Embedded` mechanism that is used [here](https://github.com/endrebjorsvik/kaifa-meter/blob/17b609639c0d73f61a1d0e86e2ef080795c7d411/kaifa_meter/decoder.py#L107). I would need some time to figure out a reasonable way to fix it.
A temporary workaround for now would be to use `construct` version 2.9 instead of 2.10:
```bash
pip install --upgrade construct==2.9
```

**Comment by gdubya** [comment]
Thanks for the quick feedback!

According to [the documentation](https://construct.readthedocs.io/en/latest/basics.html#nesting-and-embedding) the recommended way for embedding structs is using a Container.

I might have some time to try this and create a PR this weekend

**Comment by gdubya** [comment]
It looks like the upgrade might be more than just a syntactical change (I tried just changing the usages of 'Embedded' to 'Struct'). I'm not familiar enough with the construct library to see how that might be done, so i'll just leave this issue open for now.

In the meantime i've switched over to a Perl script ([ams-hand-decoder](https://github.com/robinsmidsrod/ams-han-decoder/)) for decoding the output from the meter.

**Comment by endrebjorsvik** [comment]
Since I can not make a flat structure by embedding structs anymore, I had to change the message structure to be more nested. I have created a [version 2.0.0](https://github.com/endrebjorsvik/kaifa-meter/compare/v1.0.0...v2.0.0), which is compatible with both `construct` v2.9 and 2.10. Feel free to try it out.
Just be aware that the fields for voltage, current and energy are not located in the `data` field anymore, as pointed out in the [changelog](https://github.com/endrebjorsvik/kaifa-meter/blob/master/CHANGELOG.md).
